language: cpp

compiler:
  - gcc
  - clang

before_install:
  - echo $CXX
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi #gcc
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi #clang
  - sudo apt-get update -qq
install:
  # VTK
  - sudo apt-get install -y libvtk5-dev libvtk5.8
  # gcc:
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq gcc-4.8 g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
  # clang:
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  - if [ "$CXX" == "clang++" ]; then export CXXFLAGS=""; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi
  # OpenMP
  - sudo apt-get install -y openmpi-bin libopenmpi-dev
  # ParMETIS
  - sudo apt-get install -y libparmetis-dev

env:
  - ENABLE_VTK=FALSE
  - ENABLE_VTK=TRUE
  - ENABLE_MPI=FALSE
  - ENABLE_MPI=TRUE
  - ENABLE_OPENMP=FALSE
  - ENABLE_OPENMP=TRUE
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd tests/
  - make
  - travis_wait make test

